#!/usr/bin/env python3
"""
OAuth Setup Script for Banking MCP Server

This script helps you set up OAuth authentication for your Banking MCP Server.
It provides instructions and examples for different OAuth providers.
"""

import os
import sys
from pathlib import Path

def create_env_file():
    """Create a .env file with OAuth configuration."""
    env_path = Path(".env")
    
    if env_path.exists():
        response = input(".env file already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            return
    
    print("\n🔧 Setting up OAuth configuration...\n")
    
    # Get OAuth provider details
    print("Choose your OAuth provider:")
    print("1. Custom OAuth Server")
    print("2. Microsoft Azure AD")
    print("3. Google OAuth")
    print("4. GitHub OAuth")
    
    choice = input("Enter your choice (1-4): ").strip()
    
    if choice == "1":
        setup_custom_oauth(env_path)
    elif choice == "2":
        setup_azure_ad_oauth(env_path)
    elif choice == "3":
        setup_google_oauth(env_path)
    elif choice == "4":
        setup_github_oauth(env_path)
    else:
        print("Invalid choice. Setting up custom OAuth...")
        setup_custom_oauth(env_path)

def setup_custom_oauth(env_path):
    """Setup custom OAuth provider."""
    print("\n📋 Custom OAuth Configuration:")
    
    client_id = input("Client ID [banking-mcp-server]: ").strip() or "banking-mcp-server"
    client_secret = input("Client Secret: ").strip()
    auth_endpoint = input("Authorization Endpoint [http://localhost:8080/auth/authorize]: ").strip() or "http://localhost:8080/auth/authorize"
    token_endpoint = input("Token Endpoint [http://localhost:8080/auth/token]: ").strip() or "http://localhost:8080/auth/token"
    scopes = input("Scopes [read,write,banking:access]: ").strip() or "read,write,banking:access"
    
    write_env_file(env_path, {
        "OAUTH_CLIENT_ID": client_id,
        "OAUTH_CLIENT_SECRET": client_secret,
        "OAUTH_AUTHORIZATION_ENDPOINT": auth_endpoint,
        "OAUTH_TOKEN_ENDPOINT": token_endpoint,
        "OAUTH_SCOPES": scopes,
    })

def setup_azure_ad_oauth(env_path):
    """Setup Microsoft Azure AD OAuth."""
    print("\n🔷 Microsoft Azure AD Configuration:")
    
    tenant_id = input("Azure Tenant ID: ").strip()
    client_id = input("Application (Client) ID: ").strip()
    client_secret = input("Client Secret: ").strip()
    
    if not all([tenant_id, client_id, client_secret]):
        print("❌ All fields are required for Azure AD setup!")
        return
    
    write_env_file(env_path, {
        "OAUTH_CLIENT_ID": client_id,
        "OAUTH_CLIENT_SECRET": client_secret,
        "OAUTH_AUTHORIZATION_ENDPOINT": f"https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/authorize",
        "OAUTH_TOKEN_ENDPOINT": f"https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token",
        "OAUTH_SCOPES": "openid,profile,email",
    })

def setup_google_oauth(env_path):
    """Setup Google OAuth."""
    print("\n🔵 Google OAuth Configuration:")
    
    client_id = input("Google Client ID: ").strip()
    client_secret = input("Google Client Secret: ").strip()
    
    if not all([client_id, client_secret]):
        print("❌ Client ID and Secret are required for Google OAuth!")
        return
    
    write_env_file(env_path, {
        "OAUTH_CLIENT_ID": client_id,
        "OAUTH_CLIENT_SECRET": client_secret,
        "OAUTH_AUTHORIZATION_ENDPOINT": "https://accounts.google.com/o/oauth2/v2/auth",
        "OAUTH_TOKEN_ENDPOINT": "https://oauth2.googleapis.com/token",
        "OAUTH_SCOPES": "openid,profile,email",
    })

def setup_github_oauth(env_path):
    """Setup GitHub OAuth."""
    print("\n⚫ GitHub OAuth Configuration:")
    
    client_id = input("GitHub Client ID: ").strip()
    client_secret = input("GitHub Client Secret: ").strip()
    
    if not all([client_id, client_secret]):
        print("❌ Client ID and Secret are required for GitHub OAuth!")
        return
    
    write_env_file(env_path, {
        "OAUTH_CLIENT_ID": client_id,
        "OAUTH_CLIENT_SECRET": client_secret,
        "OAUTH_AUTHORIZATION_ENDPOINT": "https://github.com/login/oauth/authorize",
        "OAUTH_TOKEN_ENDPOINT": "https://github.com/login/oauth/access_token",
        "OAUTH_SCOPES": "user:email",
    })

def write_env_file(env_path, config):
    """Write the .env file with OAuth configuration."""
    
    # Add default MCP server settings
    config.update({
        "MCP_SERVER_HOST": "0.0.0.0",
        "MCP_SERVER_PORT": "8000",
        "MCP_SERVER_BASE_URL": "http://localhost:8000",
        "OAUTH_REDIRECT_URI": "http://localhost:8000/mcp/oauth/callback",
    })
    
    with open(env_path, "w") as f:
        f.write("# OAuth Configuration for Banking MCP Server\n")
        f.write("# Generated by oauth_setup.py\n\n")
        
        for key, value in config.items():
            f.write(f"{key}={value}\n")
    
    print(f"\n✅ Configuration saved to {env_path}")
    print("\n📝 Next steps:")
    print("1. Review and adjust the .env file if needed")
    print("2. Install required dependencies: pip install python-dotenv")
    print("3. Start your MCP server: python src/app/tools/mcp_server.py")
    print("4. Test OAuth with your client application")

def main():
    print("🔐 Banking MCP Server OAuth Setup")
    print("=" * 40)
    
    # Check if we're in the right directory
    if not Path("src/app/tools/mcp_server.py").exists():
        print("❌ Please run this script from the python directory of your project")
        sys.exit(1)
    
    create_env_file()

if __name__ == "__main__":
    main()