#!/usr/bin/env python3
"""
FastMCP OAuth Setup Script

This script helps you set up OAuth authentication for your FastMCP server.
It guides you through the process of:
1. Registering an OAuth app with your chosen provider
2. Configuring environment variables
3. Testing the authentication setup
"""

import os
import subprocess
import sys
from pathlib import Path

def print_header(title):
    print(f"\n{'='*50}")
    print(f"  {title}")
    print(f"{'='*50}")

def print_step(step_num, description):
    print(f"\n📋 Step {step_num}: {description}")

def print_success(message):
    print(f"✅ {message}")

def print_warning(message):
    print(f"⚠️  {message}")

def print_error(message):
    print(f"❌ {message}")

def setup_github_oauth():
    """Guide user through GitHub OAuth setup"""
    print_header("GitHub OAuth Setup")
    
    print("""
🔗 GitHub OAuth Configuration Guide:

1. Go to GitHub Settings → Developer settings → OAuth Apps
   URL: https://github.com/settings/applications/new

2. Fill in the application details:
   - Application name: "MCP Banking Server" (or your preferred name)
   - Homepage URL: http://localhost:8000
   - Authorization callback URL: http://localhost:8000/auth/github/callback
   - Application description: "MCP server with banking tools"

3. Click "Register application"

4. Copy the Client ID and generate a new Client Secret
    """)
    
    client_id = input("Enter your GitHub OAuth Client ID: ").strip()
    if not client_id:
        print_error("Client ID is required!")
        return False
        
    client_secret = input("Enter your GitHub OAuth Client Secret: ").strip()
    if not client_secret:
        print_error("Client Secret is required!")
        return False
    
    # Create .env.oauth file
    env_file = Path(".env.oauth")
    with open(env_file, "w") as f:
        f.write(f"""# FastMCP OAuth Configuration
# Generated by setup script

# GitHub OAuth Configuration
GITHUB_CLIENT_ID={client_id}
GITHUB_CLIENT_SECRET={client_secret}

# MCP Server Configuration
MCP_SERVER_BASE_URL=http://localhost:8000
""")
    
    print_success(f"OAuth configuration saved to {env_file}")
    return True

def setup_google_oauth():
    """Guide user through Google OAuth setup"""
    print_header("Google OAuth Setup")
    
    print("""
🔗 Google OAuth Configuration Guide:

1. Go to Google Cloud Console
   URL: https://console.cloud.google.com/

2. Create a new project or select existing project

3. Enable Google+ API or Google Identity API

4. Go to APIs & Services → Credentials
   
5. Click "Create Credentials" → "OAuth client ID"
   
6. Configure OAuth consent screen if prompted

7. Application type: Web application
   - Name: "MCP Banking Server"
   - Authorized redirect URIs: http://localhost:8000/auth/google/callback

8. Copy the Client ID and Client Secret
    """)
    
    client_id = input("Enter your Google OAuth Client ID: ").strip()
    if not client_id:
        print_error("Client ID is required!")
        return False
        
    client_secret = input("Enter your Google OAuth Client Secret: ").strip()
    if not client_secret:
        print_error("Client Secret is required!")
        return False
    
    # Create .env.oauth file
    env_file = Path(".env.oauth")
    with open(env_file, "w") as f:
        f.write(f"""# FastMCP OAuth Configuration
# Generated by setup script

# Google OAuth Configuration
GOOGLE_CLIENT_ID={client_id}
GOOGLE_CLIENT_SECRET={client_secret}

# MCP Server Configuration
MCP_SERVER_BASE_URL=http://localhost:8000
""")
    
    print_success(f"OAuth configuration saved to {env_file}")
    return True

def test_configuration():
    """Test the OAuth configuration"""
    print_header("Testing Configuration")
    
    env_file = Path(".env.oauth")
    if not env_file.exists():
        print_error(".env.oauth file not found. Please run setup first.")
        return False
    
    # Try to load and validate environment
    try:
        from dotenv import load_dotenv
        load_dotenv(".env.oauth")
        
        github_id = os.getenv("GITHUB_CLIENT_ID")
        github_secret = os.getenv("GITHUB_CLIENT_SECRET")
        google_id = os.getenv("GOOGLE_CLIENT_ID")
        google_secret = os.getenv("GOOGLE_CLIENT_SECRET")
        
        if github_id and github_secret:
            print_success("GitHub OAuth credentials found")
            print(f"   Client ID: {github_id[:8]}...")
            return True
            
        elif google_id and google_secret:
            print_success("Google OAuth credentials found")
            print(f"   Client ID: {google_id[:8]}...")
            return True
            
        else:
            print_error("No valid OAuth credentials found")
            return False
            
    except ImportError:
        print_error("python-dotenv not installed. Run: pip install python-dotenv")
        return False
    except Exception as e:
        print_error(f"Configuration test failed: {e}")
        return False

def main():
    print_header("FastMCP OAuth Setup")
    
    print("""
Welcome to the FastMCP OAuth setup assistant!

This script will help you configure OAuth authentication for your MCP server.
Choose your preferred OAuth provider:

1. GitHub OAuth (recommended for development)
2. Google OAuth (enterprise-friendly)
3. Test existing configuration
4. Exit
    """)
    
    while True:
        try:
            choice = input("\nEnter your choice (1-4): ").strip()
            
            if choice == "1":
                if setup_github_oauth():
                    test_configuration()
                break
                
            elif choice == "2":
                if setup_google_oauth():
                    test_configuration()
                break
                
            elif choice == "3":
                test_configuration()
                break
                
            elif choice == "4":
                print("Exiting setup...")
                break
                
            else:
                print_warning("Please enter 1, 2, 3, or 4")
                
        except KeyboardInterrupt:
            print("\n\nSetup cancelled.")
            break
        except Exception as e:
            print_error(f"Setup error: {e}")
            break
    
    print("\n🎉 Setup complete! You can now run your MCP server with OAuth authentication.")
    print("\nNext steps:")
    print("1. Start your MCP server: python3 -m src.app.tools.mcp_server")
    print("2. The server will run with OAuth on http://localhost:8000")
    print("3. Update your MCP client to connect to the authenticated server")

if __name__ == "__main__":
    main()